### ISSUE TITLE
`gh-pages` branch does not include any extensions

### ISSUE THREAD

**Issue by Domiii** [jeromeetienne/threex-playground#1]
[The live playground](http://jeromeetienne.github.io/threex-playground/) does not add or even allow adding of any extensions, despite the fact that it's called "threex-playground"

**Comment by jeromeetienne** [comment]
it is because all extensions are automatically loaded.

to update the list, see the [docs in README.md](https://github.com/jeromeetienne/threex-playground#notes-on-updating-bowerjson)

**Comment by Domiii** [comment]
Sorry for my stupidity, maybe I'm misunderstanding something: The live playground, the one that you host yourself on your `gh-pages` branch, does not automatically load all extensions does it? And I certainly cannot change the `bower.json` file from your front-end? Do you mean, if I want any extensions, i have to install it myself? Would it be a lot of trouble to allow dynamically including extensions through the front-end?

PS: Thanks for the very swift response!

**Comment by jeromeetienne** [comment]
to add stuff from outside without cloning the repo isnt supported at the moment. you can still clone it if you want.

im not sure how much will it take to allow dynamic insert. if you implement it, i would love to have the pull request for it

**Comment by jeromeetienne** [comment]
btw one could change the html displayed on screen, to load any html you need
